#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_acme="$(acme.sh --version 2>/dev/null | grep ^v | sed 's#^v##' || true)"
  jq -n --arg acme "$ver_acme" '{acme: $acme}'
}

version "$@"
